# Generated by Django 2.2.1 on 2019-06-01 16:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_schemas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test1AUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('db', models.CharField(max_length=63)),
            ],
            bases=(django_schemas.models.Model, models.Model),
        ),
        migrations.CreateModel(
            name='Test1BCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='blue', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test1BUser')),
            ],
            bases=(django_schemas.models.Model, models.Model),
        ),
        migrations.CreateModel(
            name='Test1BLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            bases=(django_schemas.models.Model, models.Model),
        ),
        migrations.CreateModel(
            name='Test1BUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.BigIntegerField(unique=True)),
                ('color', models.CharField(default='grey', max_length=100)),
            ],
            bases=(django_schemas.models.Model, models.Model),
        ),
    ]
