# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_schemas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test1AUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('db', models.CharField(max_length=63)),
            ],
            options={
                'db_environment': 'test1-a',
            },
            bases=(django_schemas.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Test1BCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='blue', max_length=100)),
            ],
            options={
                'db_environment': 'test1-b',
            },
            bases=(django_schemas.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Test1BUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.BigIntegerField(unique=True)),
                ('color', models.CharField(default='grey', max_length=100)),
            ],
            options={
                'db_environment': 'test1-b',
            },
            bases=(django_schemas.models.BaseModel, models.Model),
        ),
        migrations.AddField(
            model_name='test1bcar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test1BUser'),
        ),
    ]
